{% set name = "pyAesCrypt" %}
{% set version = "6.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6bf8f97c03ec0e42008da911ac25e523f11f160f684d5f2bc9579ce501be9eae

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cryptography
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyAesCrypt

about:
  home: https://github.com/marcobellaccini/pyAesCrypt
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Encrypt and decrypt files and streams in AES Crypt format (version 2)

extra:
  recipe-maintainers:
    - tschoonj
